version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${BACKEND_PORT}:${BACKEND_INNER_PORT}
    command: sh -c "npm install && npm run start:dev"
    environment:
      MYSQL_HOST: database
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      BACKEND_INNER_PORT: ${BACKEND_INNER_PORT}
      JWT_SECRET: ${JWT_SECRET}

  database:
    container_name: database
    image: mariadb:10.7
    volumes:
      - mysql-db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    container_name: pma
    image: phpmyadmin:5.1.1
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USERNAME}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - database

volumes:
  mysql-db:
    driver: local